# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
