# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 04:53
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160712_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
